language: node_js

node_js:
  - "8"
sudo: false

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - npm i -g npm@5.6.0

before_script: cd interactwel/dashboard

script: npm install && npm run build